### ISSUE TITLE
Compilation fails on nightly

### ISSUE THREAD

**Issue by troplin** [dzamlo/rust-bitfield-legacy#10]
Bitfield does not compile with nightly anymore.
Unfortunately, I have no idea how to fix it, otherwise I'd have included a PR.

**Comment by dzamlo** [comment]
Thanks for the report. This should be fixed.

**Comment by troplin** [comment]
This is just crazy, everytime I open an issue with a rust repo, it's fixed within the next hour or so. 😆
Thanks! 👍
