### ISSUE TITLE
Compile-time constants as bitlengths?

### ISSUE THREAD

**Issue by BenWiederhake** [dzamlo/rust-bitfield-legacy#11]
How much work would this feature be?  I do understand that the plugin needs direct access to the actual bit length in order to compute things, but this would be nice to have.  For example, I could then write:

```Rust
pub const CARDS_PER_HAND: usize = 4;
bitfield!{PlayerState,
    cards: [3; CARDS_PER_HAND],
    has_knocked: 1,
    drinks_ordered: 2,
}
fn my_function(…) {
    /* Code that can use CARDS_PER_HAND for other things. */
}
```

I'm aware that for an actual game, using a bitfield would be a bad idea; I just wanted to avoid "foo" and "bar", and demonstrate that keeping `CARDS_PER_HAND` a `const` is actually meaningful, because now one could change the game to use 5 cards.  Or something.

Not a must-have, but I haven't seen any other issue asking for that feature.  Maybe it's out of scope if it's too much work.  I hope not :)

**Comment by dzamlo** [comment]
As far as I know, constants are not available at the time of the macros expansion. It's not possible to just use the constant like the literal int are used now.

One approach would be to keep the constant in the generated code but its complicate everything and it become impossible to determine the type (`u8`, `u16`, etc.) of the field. I'm not event sure it really possible.

Another approach would be defining the constant inside the macros invocations:
```rust
bitfield!{PlayerState,
    pub const CARDS_PER_HAND: usize = 4;
    cards: [3; CARDS_PER_HAND],
    has_knocked: 1,
    drinks_ordered: 2,
}
```
It would work, but there are some limitations. I don't really like this solution. 

A third approach would be to use macros for the constant and expand them before parsing the code, but I don't know if it's at all possible.

A last solution would be to add a macros like `bitfield_const` to define a const available for the other call to `bitfield!` (the values would be stored in a global variable in the plugin code). 

I think one of the last two solutions would be the best.

I don't really have time to research/implement this myself at the moment, but would be happy to accept a pull request.

**Comment by BenWiederhake** [comment]
> … use macros for the constant and expand them before parsing the code

Hehe, sounds like good ol' C code.

> It's not possible to just use the constant like the literal int are used now.

I hope(d) that Rust (presumably using LLVM's CTFE) can indeed do that, and evaluate the actual value of the expression at compile-time, just like `static_assert!` [seems to be able to do](https://github.com/oli-obk/rust-sa/blob/30261fdf7344ae9133cfa5b25928baa83b7ee691/tests/run-pass/example12.rs), using [`rustc_const_eval::eval_const_expr`](https://github.com/oli-obk/rust-sa/blob/30261fdf7344ae9133cfa5b25928baa83b7ee691/src/lib.rs#L39).  It's easy enough for me to read, but I would have a hard time writing this in a PR!  :-)
The linked package does the evaluation at a later compilation phase, so maybe this function can't be used.

Overall: yup, sounds like it's too much effort.  I'll just mark each place with a comment like `CARDS_PER_HAND`, and use find/replace to update it later, should the need arise.

**Comment by dzamlo** [comment]
> I hope(d) that Rust (presumably using LLVM's CTFE) can indeed do that, and evaluate the actual value of the expression at compile-time, just like `static_assert!` [seems to be able to do](https://github.com/oli-obk/rust-sa/blob/30261fdf7344ae9133cfa5b25928baa83b7ee691/tests/run-pass/example12.rs), using [`rustc_const_eval::eval_const_expr`](https://github.com/oli-obk/rust-sa/blob/30261fdf7344ae9133cfa5b25928baa83b7ee691/src/lib.rs#L39).

`static_assert!` can evaluate the constant because it runs in a later compilation phase (the part that evaluate the expression is a `LateLintPass`). When the macros are expanded, the constants are not yet available.

**Comment by BenWiederhake** [comment]
> using `rustc_const_eval::eval_const_expr`.

Turns out, the internal compiler API s not only "unstable", but *actually* unstable.  Adapting to a new-ish version of rustc [takes some effort](https://github.com/oli-obk/rust-sa/pull/3/commits/7aa0149173bd4fc513f6cb59ae919d6e30499b40), and that probably doesn't compile anymore, either.
