### ISSUE TITLE
Public bitfields

### ISSUE THREAD

**Issue by Columbus240** [dzamlo/rust-bitfield-legacy#3]
I could not find a way to declare a bitfield as public.
`pub bitfield!{X}` doesn't work, and `pub_bitfield!{X}` doesn't exist as far as I can tell.
But this would be a nice feature to have.

**Comment by dzamlo** [comment]
Thank you very much for your idea. 

Now, you can use the `pub` keyword inside the macro to declare a bitfield and each of its fields as public, in a way similar to what you can do with a `struct`.
