### ISSUE TITLE
`#![deny(missing_docs)]`

### ISSUE THREAD

**Issue by Columbus240** [dzamlo/rust-bitfield-legacy#4]
I'm working on a project where in the topmost module `#![deny(missing_docs)]` is specified.
Cargo blocks the build, because the struct generated by the `bitfield` macro has fields without documentation and it is declared public.
Providing `#[allow(missing_docs)]` does not help (I don't know why).

So a fixing patch would either generate documentation for every thing in a `bitfield` and makes it pass the documentation lint, or a matching allow(missing_docs) is inserted.

**Comment by Columbus240** [comment]
Sorry, submitted too early. In the last sentence I meant `#[allow(missing_docs)]`.

**Comment by dzamlo** [comment]
The stuff you put before the macro invocation (like attributes or keyword) doesn't apply to the items generated by the macro. This is why the `#[allow(missing_docs)]`doesn't help.
