### ISSUE TITLE
Document fields of bitfield

### ISSUE THREAD

**Issue by Columbus240** [dzamlo/rust-bitfield-legacy#5]
It might be useful to be able to add documentation comments to the (custom) fields of a public bitfield, because they are part of the public API.
I haven't encountered the need for this just yet, but it could come up later.

**Comment by dzamlo** [comment]
Implemented in d893497.

With the current implementation, the documentation comments for the getter and setter are the same. But I think this is enough for most use case.

**Comment by Columbus240** [comment]
Thank you for your speed of issue fixing.
