### ISSUE TITLE
Empty bitfields

### ISSUE THREAD

**Issue by Columbus240** [dzamlo/rust-bitfield-legacy#6]
Empty bitfields have an unused field "data", which triggers the `(unused_code)` lint.

**Comment by dzamlo** [comment]
Is there any legitimate use of an empty bitfield ?

**Comment by Columbus240** [comment]
Honestly, I used the bitfield as placeholder to have fields added later (in about 2-3 months). The function that used the empty bitfield did nothing with it, so there was also an `(unused_code)`.
If it is possible and not too complicated for you to find out if a bitfield is empty, that then the struct would not have a data field, or similar.
I agree that there's no reasonable production use for it. An empty struct could be used. But while sketching some code, it gives an unusual warning.
Once more: it would be nice to have, would make things kinda consistent, but it surely is not something that reasonable code should depend upon.

**Comment by dzamlo** [comment]
I also removed the new method, because I think it doesn't make sens for an empty bitfield. What do you think of that ?
