### ISSUE TITLE
Static Construction

### ISSUE THREAD

**Issue by cptroot** [dzamlo/rust-bitfield-legacy#7]
I'm interested in using a bitfield in a static declaration. I have a bitfield like this:

```
bitfield!{                                                                                                 
#[derive(Clone, Copy)]
    InterruptDescriptor,
    reserved: 32,
    offset_high: 32,
    offset_med: 16,
    present_flag: 1,
    descriptor_privilege_level: 2,
    _zeros_one: 1,
    gate_type: 4,
    _zeros_two: 5,
    ist: 3,
    segment_selector: 16,
    offset_low: 16,
}
```

And I wish to use it in a static declaration:

```
static mut idt: [InterruptDescriptor; INTR_CNT] = [InterruptDescriptor::new([0;16]);INTR_CNT];
```

But when I do that, Rust complains with: `error: function calls in statics are limited to constant functions, struct and enum constructors [E0015]`

Do you have any ideas on how I can fix this? My current idea is just to have this be uninitialized at the start of the program and then modify it later, but I feel like there might be a better solution.

**Comment by dzamlo** [comment]
Currently, you may be able to use lazy_static!.

 I will implement a better solution very soon.

I can either make the new constructor const, or make the only field of the generated struct pub.
I don't know what is the better choice.

**Comment by dzamlo** [comment]
The solution I choose is to add two attributes. One to make the constructor const, the other to make the field public. See `examples/static.rs` for more details.

**Comment by cptroot** [comment]
Thanks!
