### ISSUE TITLE
Why do the bitfields need to have fields between 0 and <= 64?

### ISSUE THREAD

**Issue by AeroNotix** [dzamlo/rust-bitfield-legacy#8]
Some protocols have fields larger than 64. Is there a plan to implement larger bitfields? The code seems to get a bit at a time, so I'm not seeing a technical reason to need smaller than 64 bits. Unless it's because rust doesn't have integer types larger than 64 bit?

**Comment by dzamlo** [comment]
>  Unless it's because rust doesn't have integer types larger than 64 bit?

That's exactly the reason: the values of the fields are returned in an integer and the largest integer type in rust is 64 bits.

Depending on the situation, you can use an array field. In the ipv4 example, I use them for the addresses.

Do you have a specific example of a protocol with fields larger than 64 bits ? And do you have an idea of what the interface could look like for field larger that 64 bits ?

**Comment by AeroNotix** [comment]
UUIDs, custom identifier types.

**Comment by dzamlo** [comment]
I think these use cases are covered by array fields, and methods implemented on the top of the getter setter provided by `bitfield!`.
